version: 2.6.{build}.0
image: Visual Studio 2019
cache:
- C:\projects\DMF
environment:
  DmfRootPath: C:\projects\DMF
platform:
- x86
- x64
- ARM64
configuration:
- Release
install:
- ps: Invoke-WebRequest https://wixtoolset.org/downloads/v3.14.0.6526/wix314-binaries.zip -OutFile .\wix314-binaries.zip
- ps: Expand-Archive .\wix314-binaries.zip -DestinationPath .\wix
- cmd: git submodule -q update --init
- cmd: git clone -q https://github.com/microsoft/DMF.git C:\projects\DMF 2> nul || set ERRORLEVEL=0
- cmd: |
    cd "C:\projects\DMF"
    git pull > NUL
    git apply "%APPVEYOR_BUILD_FOLDER%\patches\dmf-optimizations.diff
    git apply "%APPVEYOR_BUILD_FOLDER%\patches\dmf-sdk10.0.19041.0.diff
    cd %appveyor_build_folder%
before_build:
- cmd: nuget restore
- ps: Invoke-WebRequest "https://github.com/nefarius/vpatch/releases/latest/download/vpatch.exe" -OutFile vpatch.exe
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\BthPS3\BthPS3.vcxproj" --vcxproj.inf-time-stamp
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\BthPS3\BthPS3.rc" --resource.file-version --resource.product-version
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\BthPS3PSM\BthPS3PSM.vcxproj" --vcxproj.inf-time-stamp
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\BthPS3PSM\BthPS3PSM.rc" --resource.file-version --resource.product-version
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\BthPS3Util\BthPS3Util.rc" --resource.file-version --resource.product-version
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\Setup\BthPS3CA\BthPS3CA.rc" --resource.file-version --resource.product-version
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\BthPS3CfgUI\Properties\AssemblyInfo.cs" --assembly.version --assembly.file-version
build_script:
- cmd: .\build.cmd
after_build:
- cmd: makecab.exe /f .\setup\BthPS3_%PLATFORM%.ddf
artifacts:
- path: 'bin**\BthPS3\*.inf'
- path: 'bin**\BthPS3\*.sys'
- path: 'bin**\BthPS3PSM\*.inf'
- path: 'bin**\BthPS3PSM\*.sys'
- path: 'bin**\*.pdb'
- path: 'disk1\*.cab'
- path: 'bin**\*.exe'
- path: 'bin**\*.dll'
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true